CREATE TABLE objects (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  primary_image VARCHAR(255),
  object_type VARCHAR(255) NOT NULL,
  object_medium VARCHAR(255) NOT NULL,
  width DECIMAL(5, 1),
  height DECIMAL(5, 1),
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  object_display_date DATE,
  object_begin_date DATE,
  object_end_date DATE,
  period VARCHAR(255),
  artist_display_name VARCHAR(255),
  artist_display_bio VARCHAR(255),
  artist_nationality VARCHAR(255),
  artist_begin_date DATE,
  artist_end_date DATE,
  credit_line VARCHAR(255),
  repository VARCHAR(255),
  rights_and_reproduction VARCHAR(255),
  is_public_domain BOOLEAN,
  ref_url VARCHAR(255),
  wikidata_URL VARCHAR(255),
  record_created_at TIMESTAMP DEFAULT NOW(),
  record_last_updated TIMESTAMP DEFAULT NOW(),
  INDEX object_medium (object_medium),
  INDEX title (title),
  INDEX object_display_date (object_display_date),
  INDEX artist_display_name (artist_display_name)
) ENGINE = innodb DEFAULT CHARSET = UTF8MB4 DEFAULT COLLATE = UTF8MB4_unicode_ci;